"""
HireSense AI — model card generator.

Produces MODEL_CARD.md, a responsible-AI document describing the model's
purpose, data, performance, fairness, and limitations. Regenerate it after
each training run so the card always reflects the current model.

    python src/model_card.py
"""
import pandas as pd

from config import (
    DATASET_PATH,
    GROUP_COLUMN,
    NUMERIC_FEATURES,
    ROOT_DIR,
    TARGET,
)
from fairness import audit, summarize
from predict import load_model

CARD_PATH = ROOT_DIR / "MODEL_CARD.md"


def generate() -> str:
    bundle = load_model()
    model = bundle["model"]
    df = pd.read_csv(DATASET_PATH)

    fairness_block = "_Protected attribute not present in dataset._"
    if GROUP_COLUMN in df.columns:
        summary = summarize(audit(model, df))
        fairness_block = (
            f"- Demographic parity difference: **{summary['demographic_parity_difference']:.4f}**\n"
            f"- Disparate impact ratio: **{summary['disparate_impact_ratio']:.4f}** "
            f"({'passes' if summary['disparate_impact_ratio'] >= 0.8 else 'fails'} the 80% rule)\n"
            f"- Equal-opportunity difference: **{summary['equal_opportunity_difference']:.4f}**"
        )

    pos = int(df[TARGET].sum())
    features_list = "\n".join(f"- `{f}`" for f in NUMERIC_FEATURES)

    return f"""# Model Card — HireSense AI

## Model details
- **Name:** HireSense AI applicant screener
- **Version:** {bundle.get('version', 'unknown')}
- **Algorithm:** Support Vector Machine ({bundle.get('tuning', 'gridsearch')}-tuned, calibrated)
- **Trained at:** {bundle.get('trained_at', 'unknown')}
- **Best hyperparameters:** `{bundle.get('best_params', {})}`

## Intended use
- **Purpose:** Assist recruiters by ranking/screening job applicants into
  *shortlist* vs *reject*, with a calibrated confidence score.
- **Intended users:** Hiring teams, as a **decision-support** tool.
- **Out of scope:** Fully automated hiring/rejection without human review;
  use on populations unlike the training data.

## Training data
- **Source:** Synthetic, generated to be realistic and reproducible
  (no real personal data).
- **Size:** {len(df)} applicants ({pos} shortlisted, {len(df) - pos} rejected).
- **Features:**
{features_list}

## Performance (held-out test set)
- **Accuracy:** {bundle.get('test_accuracy', float('nan')):.3f}
- **ROC-AUC:** {bundle.get('test_roc_auc', float('nan')):.3f}

## Fairness
Audited on the synthetic protected attribute `{GROUP_COLUMN}` (never used as a
model feature):

{fairness_block}

## Limitations & ethical considerations
- Trained on **synthetic** data; real-world performance will differ and must
  be re-validated on real, representative data before any deployment.
- Screening models can encode historical bias. Always keep a human in the loop,
  monitor selection rates by group, and audit regularly (`src/fairness.py`).
- Probabilities are calibrated but not infallible; use conformal prediction
  (`src/conformal.py`) to flag uncertain cases for manual review.
- Not a legal-compliance tool. Ensure use complies with local employment law.

_This card is auto-generated by `src/model_card.py`._
"""


def main() -> None:
    CARD_PATH.write_text(generate())
    print(f"✓ Model card written to {CARD_PATH}")


if __name__ == "__main__":
    main()
